---
- hosts: controller
  user: vagrant
  sudo: True
  gather_facts: True
  vars_files:
    - ../global_vars.yaml

  tasks:
  - include: ../prereq/setup.yaml
  - name: ensure apt repo is up to date
    action: apt update-cache=yes

  - name: ensure keystone packages are installed
    action: apt pkg=$item
    with_items:
      - ntp # http://docs.openstack.org/essex/openstack-compute/install/apt/content/installing-ntp.html
      - keystone # http://docs.openstack.org/essex/openstack-compute/install/apt/content/install-keystone.html
      - python-mysqldb # http://docs.openstack.org/essex/openstack-compute/install/apt/content/install-keystone.html
      - mysql-server # http://docs.openstack.org/essex/openstack-compute/install/apt/content/install-keystone.html
      - python-yaml # http://docs.openstack.org/essex/openstack-compute/install/apt/content/setting-up-tenants-users-and-roles.html

  # http://docs.openstack.org/essex/openstack-compute/install/apt/content/installing-ntp.html
  - name: update ntp.conf file for server
    action: copy src=files/ntp.conf dest=/etc/ntp.conf owner=root group=root mode=0644

  # http://docs.openstack.org/essex/openstack-compute/install/apt/content/install-keystone.html
  - name: ensure sqlite keystone database is deleted
    action: file dest=/var/lib/keystone/keystone.db state=absent
  - name: mysql config file that binds to all interfaces
    action: copy src=files/my.cnf dest=/etc/mysql/my.cnf owner=root group=root mode=0644
  - name: ensure mysql restarted for config change to take effect
    action: service name=mysql state=restarted

  - name: ensure keystone database is present
    action: mysql_db name=keystone
    notify:
      - populate keystone database

  - name: ensure keystone database user is present
    action: mysql_user name=keystone host=% password=${keystone_db_password} priv=keystone.*:ALL

    # See the following links for why anonymous mysql users cause problems:
    # http://www.tikalk.com/alm/blog/solution-mysql-error-1045-access-denied-userlocalhost-breaks-openstack
    # http://lists.mysql.com/mysql/128381
  - name: ensure anonymous users removed from mysql
    action: mysql_user name='' host=$item state=absent
    with_items:
      - localhost
      - ${ansible_hostname}

  - name: ensure keystone config script is present
    action: template src=templates/keystone.conf dest=/etc/keystone/keystone.conf owner=root group=root mode=0644
  - name: ensure keystone service restarted
    action: service name=keystone state=restarted
  - name: ensure keystone database is synced
    action: command /usr/bin/keystone-manage db_sync

  - name: ensure keystone init script present
    action: template src=files/keystone_init.sh dest=/tmp/keystone_init.sh owner=root group=root mode=0755
#  - name: ensure kestyone-config.yaml is present
#    action: template src=templates/keystone-config.yaml dest=/tmp/keystone-config.yaml owner=root group=root mode=0600

  handlers:
  - name: populate keystone database
    action: shell /tmp/keystone_init.sh

