---
- hosts: controller
  user: vagrant
  sudo: True
  gather_facts: False
  vars_files:
    - ../global_vars.yaml

  tasks:
  - name: ensure glance is installed
    action: apt pkg=$item
    with_items:
      - glance
      - glance-api
      - glance-common
      - python-glanceclient
      - glance-registry
      - python-glance

  - name: ensure glance sqlite is deleted
    action: file dest=/var/lib/glance/glance.sqlite state=absent

    # http://docs.openstack.org/essex/openstack-compute/install/apt/content/configure-glance-mysql.html
  - name: ensure glance database is present
    action: mysql_db name=glance
    notify:
      - version glance database
      - populate glance database
      - restart glance-registry

  - name: ensure glance database user is present
    action: mysql_user name=glance host=% password=${glance_db_password} priv=glance.*:ALL

  - name: ensure glance-api-paste.ini file is up to date
    action: template src=templates/glance-api-paste.ini dest=/etc/glance/glance-api-paste.ini owner=glance group=glance mode=0644
    notify:
    - restart glance-api

  - name: ensure glance-api.conf file is up to date
    action: template src=templates/glance-api.conf dest=/etc/glance/glance-api.conf owner=glance group=glance mode=0644
    notify:
    - restart glance-api

  - name: ensure glance-registry.conf file is up to date
    action: template src=templates/glance-registry.conf dest=/etc/glance/glance-registry.conf owner=glance group=glance mode=0644
    notify:
    - restart glance-registry

  - name: ensure glance-registry-paste.ini file is up to date
    action: copy src=files/glance-registry-paste.ini dest=/etc/glance/glance-registry-paste.ini owner=glance group=glance mode=0644
    notify:
    - restart glance-registry

  handlers:
  - name: version glance database
    action: command glance-manage version_control 0

  - name: populate glance database
    action: command glance-manage db_sync

  - name: restart glance-registry
    action: service name=glance-registry state=restarted

  - name: restart glance-api
    action: service name=glance-api state=restarted


- hosts: controller
  user: vagrant
  gather_facts: False
  vars_files:
    - ../global_vars.yaml
  tags:
    - image

  tasks:
  - name: ensure temporary image directory exists
    action: file dest=/tmp/images state=directory

  - name: ensure test image has been obtained
    action: get_url url=https://launchpad.net/cirros/trunk/0.3.0/+download/cirros-0.3.0-x86_64-disk.img dest=/tmp/images/cirros.img
    notify:
    - add image to glance

#  - name: ensure openrc file has been copied
#    action: copy src=../../openrc dest=/home/vagrant/openrc

  handlers:
  - name: add image to glance
    action: shell /usr/bin/glance --os-username=admin --os-password=${default_admin_password} --os-tenant-name=admin --os-auth-url=http://127.0.0.1:5000/v2.0 image-create --name=cirros-0.3.0-x86_64 --disk-format=qcow2 --container-format=bare < /tmp/images/cirros.img
